using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace SkyUK.Utils
{
  public static class SkyUtils
  {
    public const string REGIONS = "4097-14=England(BBC) / Border & NW(ITV)\r\n4097-12=England(BBC) / Border(ITV)\r\n4097-29=England(BBC) / E Mid & Yorkshire(ITV)\r\n4097-27=England(BBC) / E London & Midlands(ITV)\r\n4097-18=England(BBC) / East London & SE(ITV)\r\n4097-25=England(BBC) / East & Midlands(ITV)\r\n4097-21=England(BBC) / East & Yorkshire(ITV)\r\n4097-2=England(BBC) / East(ITV)\r\n4097-11=England(BBC) / London & SE(ITV)\r\n4097-9=England(BBC) / London & South(ITV)\r\n4097-1=England(BBC) / London(ITV)\r\n4097-19=England(BBC) / Midlands & NW(ITV)\r\n4097-24=England(BBC) / Midlands & West(ITV)\r\n4097-3=England(BBC) / Midlands(ITV)\r\n4097-20=England(BBC) / Midlands & Yorkshire(ITV)\r\n4097-26=England(BBC) / NE & Yorkshire(ITV)\r\n4097-17=England(BBC) / NW & Wales(ITV)\r\n4097-13=England(BBC) / North East(ITV)\r\n4097-7=England(BBC) / North West(ITV)\r\n4097-5=England(BBC) / South(ITV)\r\n4097-10=England(BBC) / South East(ITV)\r\n4097-6=England(BBC) / South West(ITV)\r\n4097-4=England(BBC) / West(ITV)\r\n4097-8=England(BBC) / Yorkshire(ITV)\r\n4099-73=England 2 / Isle Of Man(bh)\r\n4099-65=England 2 / Brighton\r\n4099-63=England 2 / HTV W/Thames Valley(bv)\r\n4099-70=England 2 / Henley On Thames\r\n4099-66=England 2 / London / Thames Valley\r\n4099-64=England 2 / London Kent\r\n4099-68=England 2 / Meridian North\r\n4099-62=England 2 / North East Midlands(bu)\r\n4099-71=England 2 / Oxford\r\n4099-61=England 2 / Scarborough(bc)\r\n4099-60=England 2 / Sheffield(au)\r\n4099-72=England 2 / South Yorkshire\r\n4099-69=England 2 / Tees\r\n4099-67=England 2 / West Dorset\r\n4099-41=Wales(BBC) / Midlands(ITV)\r\n4099-42=Wales(BBC) / North West(ITV)\r\n4099-43=Wales(BBC) / Wales(ITV)\r\n4099-45=Wales(BBC) / NW & Wales(ITV)\r\n4100-33=Northern Ireland(BBC & ITV)\r\n4100-34=Channel Isles(ITV)\r\n4100-50=Republic of Ireland 4100\r\n4098-36=Scotland(BBC) / Border(ITV)\r\n4098-38=Scotland(BBC) / C Scot & N Scot(ITV)\r\n4098-37=Scotland(BBC) / Central Scotland(ITV)\r\n4098-35=Scotland(BBC) / North Scotland(ITV)";
    const string UK_CATEGORIES = "70=Entertainment\r\n1F=Lifestyle & Culture\r\nD0=Movies\r\n9F=Music\r\nF0=Sports\r\nB0=News\r\n7F=Documentaries\r\nBF=Religion\r\n50=Kids\r\n30=Shopping\r\nDF=International\r\n5F=Gaming & Dating\r\nFF=Specialist\r\n3F=Adult\r\n10=Sky Help";

    public static Dictionary<string, string> GetUKCategories()
    {
      Dictionary<string, string> categoriesDictionary = new Dictionary<string, string>();
      string[] categories = UK_CATEGORIES.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);
      foreach (string category in categories)
      {
        string[] keyVal = category.Split('=');
        categoriesDictionary.Add(keyVal[0], keyVal[1]);
      }
      return categoriesDictionary;
    }

    public static string[] GetUKHuffmanDictionary()
    {
      using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("SkyUK.Utils.UKDict.txt"))
      using (var reader = new StreamReader(stream))
        return reader.ReadToEnd().Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);
    }

    public static Dictionary<int, string> GetThemes()
    {
      Dictionary<int, string> themes = new Dictionary<int, string>();
      themes.Add(0x0, "No Category");
      themes.Add(0x1, "");
      themes.Add(0x2, "");
      themes.Add(0x3, "");
      themes.Add(0x4, "");
      themes.Add(0x5, "");
      themes.Add(0x6, "");
      themes.Add(0x7, "");
      themes.Add(0x8, "");
      themes.Add(0x9, "");
      themes.Add(0xa, "");
      themes.Add(0xb, "");
      themes.Add(0xc, "");
      themes.Add(0xd, "");
      themes.Add(0xe, "");
      themes.Add(0xf, "");
      themes.Add(0x10, "");
      themes.Add(0x11, "");
      themes.Add(0x12, "");
      themes.Add(0x13, "");
      themes.Add(0x14, "");
      themes.Add(0x15, "");
      themes.Add(0x16, "");
      themes.Add(0x17, "");
      themes.Add(0x18, "");
      themes.Add(0x19, "");
      themes.Add(0x1a, "");
      themes.Add(0x1b, "");
      themes.Add(0x1c, "");
      themes.Add(0x1d, "");
      themes.Add(0x1e, "");
      themes.Add(0x1f, "");
      themes.Add(0x20, "Specialist - Undefined");
      themes.Add(0x21, "Specialist - Adult");
      themes.Add(0x22, "Specialist - Events");
      themes.Add(0x23, "Specialist - Shopping");
      themes.Add(0x24, "Specialist - Gaming");
      themes.Add(0x25, "");
      themes.Add(0x26, "");
      themes.Add(0x27, "");
      themes.Add(0x28, "");
      themes.Add(0x29, "");
      themes.Add(0x2a, "");
      themes.Add(0x2b, "");
      themes.Add(0x2c, "");
      themes.Add(0x2d, "");
      themes.Add(0x2e, "");
      themes.Add(0x2f, "");
      themes.Add(0x30, "");
      themes.Add(0x31, "");
      themes.Add(0x32, "");
      themes.Add(0x33, "");
      themes.Add(0x34, "");
      themes.Add(0x35, "");
      themes.Add(0x36, "");
      themes.Add(0x37, "");
      themes.Add(0x38, "");
      themes.Add(0x39, "");
      themes.Add(0x3a, "");
      themes.Add(0x3b, "");
      themes.Add(0x3c, "");
      themes.Add(0x3d, "");
      themes.Add(0x3e, "");
      themes.Add(0x3f, "");
      themes.Add(0x40, "Children - Undefined");
      themes.Add(0x41, "Children - Cartoons");
      themes.Add(0x42, "Children - Comedy");
      themes.Add(0x43, "Children - Drama");
      themes.Add(0x44, "Children - Educational");
      themes.Add(0x45, "Children - Under 5");
      themes.Add(0x46, "Children - Factual");
      themes.Add(0x47, "Children - Magazine");
      themes.Add(0x48, "Children - Games Shows");
      themes.Add(0x49, "Children - Games");
      themes.Add(0x4a, "");
      themes.Add(0x4b, "");
      themes.Add(0x4c, "");
      themes.Add(0x4d, "");
      themes.Add(0x4e, "");
      themes.Add(0x4f, "");
      themes.Add(0x50, "");
      themes.Add(0x51, "");
      themes.Add(0x52, "");
      themes.Add(0x53, "");
      themes.Add(0x54, "");
      themes.Add(0x55, "");
      themes.Add(0x56, "");
      themes.Add(0x57, "");
      themes.Add(0x58, "");
      themes.Add(0x59, "");
      themes.Add(0x5a, "");
      themes.Add(0x5b, "");
      themes.Add(0x5c, "");
      themes.Add(0x5d, "");
      themes.Add(0x5e, "");
      themes.Add(0x5f, "");
      themes.Add(0x60, "Entertainment - Undefined");
      themes.Add(0x61, "Entertainment - Action");
      themes.Add(0x62, "Entertainment - Comedy");
      themes.Add(0x63, "Entertainment - Detective");
      themes.Add(0x64, "Entertainment - Drama");
      themes.Add(0x65, "Entertainment - Game Show");
      themes.Add(0x66, "Entertainment - Sci-FI");
      themes.Add(0x67, "Entertainment - Soap");
      themes.Add(0x68, "Entertainment - Animation");
      themes.Add(0x69, "Entertainment - Chat Show");
      themes.Add(0x6a, "Entertainment - Cooking");
      themes.Add(0x6b, "Entertainment - Factual");
      themes.Add(0x6c, "Entertainment - Fashion");
      themes.Add(0x6d, "Entertainment - Gardening");
      themes.Add(0x6e, "Entertainment - Travel");
      themes.Add(0x6f, "Entertainment - Technology");
      themes.Add(0x70, "Entertainment - Arts");
      themes.Add(0x71, "Entertainment - Lifestyle");
      themes.Add(0x72, "Entertainment - Home");
      themes.Add(0x73, "Entertainment - Magazine");
      themes.Add(0x74, "Entertainment - Medical");
      themes.Add(0x75, "Entertainment - Review");
      themes.Add(0x76, "Entertainment - Antiques");
      themes.Add(0x77, "Entertainment - Motors");
      themes.Add(0x78, "Entertainment - Art&Lit");
      themes.Add(0x79, "Entertainment - Ballet");
      themes.Add(0x7a, "Entertainment - Opera");
      themes.Add(0x7b, "");
      themes.Add(0x7c, "");
      themes.Add(0x7d, "");
      themes.Add(0x7e, "");
      themes.Add(0x7f, "");
      themes.Add(0x80, "Music & Radio - Undefined");
      themes.Add(0x81, "Music & Radio - Classical");
      themes.Add(0x82, "Music & Radio - Folk and Country");
      themes.Add(0x83, "Music & Radio - National Music");
      themes.Add(0x84, "Music & Radio - Jazz");
      themes.Add(0x85, "Music & Radio - Opera");
      themes.Add(0x86, "Music & Radio - Rock&Pop");
      themes.Add(0x87, "Music & Radio - Alternative Music");
      themes.Add(0x88, "Music & Radio - Events");
      themes.Add(0x89, "Music & Radio - Club and Dance");
      themes.Add(0x8a, "Music & Radio - Hip Hop");
      themes.Add(0x8b, "Music & Radio - Soul/R&B");
      themes.Add(0x8c, "Music & Radio - Dance");
      themes.Add(0x8d, "Music & Radio - Ballet");
      themes.Add(0x8e, "");
      themes.Add(0x8f, "Music & Radio - Current Affairs");
      themes.Add(0x90, "Music & Radio - Features");
      themes.Add(0x91, "Music & Radio - Arts & Lit.");
      themes.Add(0x92, "Music & Radio - Factual");
      themes.Add(0x93, "");
      themes.Add(0x94, "");
      themes.Add(0x95, "Music & Radio - Lifestyle");
      themes.Add(0x96, "Music & Radio - News and Weather");
      themes.Add(0x97, "Music & Radio - Easy Listening");
      themes.Add(0x98, "Music & Radio - Discussion");
      themes.Add(0x99, "Music & Radio - Entertainment");
      themes.Add(0x9a, "Music & Radio - Religious");
      themes.Add(0x9b, "");
      themes.Add(0x9c, "");
      themes.Add(0x9d, "");
      themes.Add(0x9e, "");
      themes.Add(0x9f, "");
      themes.Add(0xa0, "News & Documentaries - Undefined");
      themes.Add(0xa1, "News & Documentaries - Business");
      themes.Add(0xa2, "News & Documentaries - World Cultures");
      themes.Add(0xa3, "News & Documentaries - Adventure");
      themes.Add(0xa4, "News & Documentaries - Biography");
      themes.Add(0xa5, "News & Documentaries - Educational");
      themes.Add(0xa6, "News & Documentaries - Feature");
      themes.Add(0xa7, "News & Documentaries - Politics");
      themes.Add(0xa8, "News & Documentaries - News");
      themes.Add(0xa9, "News & Documentaries - Nature");
      themes.Add(0xaa, "News & Documentaries - Religious");
      themes.Add(0xab, "News & Documentaries - Science");
      themes.Add(0xac, "News & Documentaries - Showbiz");
      themes.Add(0xad, "News & Documentaries - War Documentary");
      themes.Add(0xae, "News & Documentaries - Historical");
      themes.Add(0xaf, "News & Documentaries - Ancient");
      themes.Add(0xb0, "News & Documentaries - Transport");
      themes.Add(0xb1, "News & Documentaries - Docudrama");
      themes.Add(0xb2, "News & Documentaries - World Affairs");
      themes.Add(0xb3, "News & Documentaries - Features");
      themes.Add(0xb4, "News & Documentaries - Showbiz");
      themes.Add(0xb5, "News & Documentaries - Politics");
      themes.Add(0xb6, "News & Documentaries - Transport");
      themes.Add(0xb7, "News & Documentaries - World Affairs");
      themes.Add(0xb8, "");
      themes.Add(0xb9, "");
      themes.Add(0xba, "");
      themes.Add(0xbb, "");
      themes.Add(0xbc, "");
      themes.Add(0xbd, "");
      themes.Add(0xbe, "");
      themes.Add(0xbf, "");
      themes.Add(0xc0, "Movie");
      themes.Add(0xc1, "Movie - Action");
      themes.Add(0xc2, "Movie - Animation");
      themes.Add(0xc3, "");
      themes.Add(0xc4, "Movie - Comedy");
      themes.Add(0xc5, "Movie - Family");
      themes.Add(0xc6, "Movie - Drama");
      themes.Add(0xc7, "");
      themes.Add(0xc8, "Movie - Sci-Fi");
      themes.Add(0xc9, "Movie - Thriller");
      themes.Add(0xca, "Movie - Horror");
      themes.Add(0xcb, "Movie - Romance");
      themes.Add(0xcc, "Movie - Musical");
      themes.Add(0xcd, "Movie - Mystery");
      themes.Add(0xce, "Movie - Western");
      themes.Add(0xcf, "Movie - Factual");
      themes.Add(0xd0, "Movie - Fantasy");
      themes.Add(0xd1, "Movie - Erotic");
      themes.Add(0xd2, "Movie - Adventure");
      themes.Add(0xd3, "Movies - War");
      themes.Add(0xd4, "");
      themes.Add(0xd5, "");
      themes.Add(0xd6, "");
      themes.Add(0xd7, "");
      themes.Add(0xd8, "");
      themes.Add(0xd9, "");
      themes.Add(0xda, "");
      themes.Add(0xdb, "");
      themes.Add(0xdc, "");
      themes.Add(0xdd, "");
      themes.Add(0xde, "");
      themes.Add(0xdf, "");
      themes.Add(0xe0, "Sports - Undefined");
      themes.Add(0xe1, "Sports - American Football");
      themes.Add(0xe2, "Sports - Athletics");
      themes.Add(0xe3, "Sports - Baseball");
      themes.Add(0xe4, "Sports - Basketball");
      themes.Add(0xe5, "Sports - Boxing");
      themes.Add(0xe6, "Sports - Cricket");
      themes.Add(0xe7, "Sports - Fishing");
      themes.Add(0xe8, "Sports - Football");
      themes.Add(0xe9, "Sports - Golf");
      themes.Add(0xea, "Sports - Ice Hockey");
      themes.Add(0xeb, "Sports - Motor Sport");
      themes.Add(0xec, "Sports - Racing");
      themes.Add(0xed, "Sports - Rugby");
      themes.Add(0xee, "Sports - Equestrian");
      themes.Add(0xef, "Sports - Winter Sports");
      themes.Add(0xf0, "Sports - Snooker / Pool");
      themes.Add(0xf1, "Sports - Tennis");
      themes.Add(0xf2, "Sports - Wrestling");
      themes.Add(0xf3, "Sports - Darts");
      themes.Add(0xf4, "Sports - Watersports");
      themes.Add(0xf5, "Sports - Extreme");
      themes.Add(0xf6, "Sports - Other");
      themes.Add(0xf7, "");
      themes.Add(0xf8, "");
      themes.Add(0xf9, "");
      themes.Add(0xfa, "");
      themes.Add(0xfb, "");
      themes.Add(0xfc, "");
      themes.Add(0xfd, "");
      themes.Add(0xfe, "");
      themes.Add(0xff, "");
      return themes;
    }
  }
}
